apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexora
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexora
  template:
    metadata:
      labels:
        app: nexora
    spec:
      containers:
        - name: nexora
          image: nexora:1.0.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
